### ISSUE TITLE
Indicate power mode e.g. with icon colour

### ISSUE THREAD

**Issue by mortenfyhn** [MetaFight/PowerBuddy#7]
Hi, I love this little program, and have a feature request.

What about having the icon change colors based on the current power scheme? Something like green for power saving, yellow for balanced, red for performance. Especially useful for those who find that Windows changes the power mode unpredictably.

**Comment by MetaFight** [comment]
Hi @mortenfyhn, that's an interesting idea with some interesting technical problems.

I'm not actually sure how to reliably map a color to a specific power plan.  This is because users can create their own power plans, they can rename existing power plans, and I'm not sure if the three power plans you list (Power Saving, Balanced, High Performance) are actually universal.

Unless these powerplans share the same GUID across all systems, I think it would be pretty hard to guarantee this works for everyone.

I'll look into it.

**Comment by mortenfyhn** [comment]
That's a good point. What about instead of having a fixed colourmap (or even a default map), you could let users create their own map by manually selecting a colour for each plan in the dropdown list? Do you reckon that would be better/more feasible?

**Comment by MetaFight** [comment]
That's a pretty good idea.

I'll have to look into how to generate the required tray icon, but that should be too hard.

**Comment by MetaFight** [comment]
TODO

1. Export the current SVG icon to XAML.
1. Add color selection UI.  This should show a preview of the icon using the above XAML.
  (Consider show a preview for a bunch of different icon sizes)
1. When user confirms, generate required bitmaps and save as `.ico` file.
1. Update tray icon.

**Comment by MetaFight** [comment]
These changes can be found in release 1.3.0.0:
https://github.com/MetaFight/PowerBuddy/releases/tag/1.3.0.0

**Comment by MetaFight** [comment]
Implemented in https://github.com/MetaFight/PowerBuddy/releases/tag/1.3.0.0
